-- autogenerated from quickshell colors.json
local M = {}

M.colors = {
    background = '#191112',
    foreground = '#e0e0e0',
    selection  = '#e4bdc2',
    comment    = '#757575',
    keyword    = '#ebbe90',
    string     = '#f0dee0',
    number     = '#ffb4ab',
}

return M
